---
apiVersion: v1
kind: Pod
metadata:
  name: vnf3
  namespace: default
  labels:
    sfc: "true"
spec:
  containers:
    - name: "vnf3"
      image: ligato/vpp-agent-arm64:dev
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
      ports:
        - containerPort: 5002
      env:
        - name: MICROSERVICE_LABEL
          value: vnf3
      volumeMounts:
        - name: vpp-config
          mountPath: /etc/vpp
        - name: agent-config
          mountPath: /opt/vpp-agent/dev
        - name: memif-sockets
          mountPath: /var/run/contiv
      resources:
        limits:
          hugepages-1Gi: 2Gi
          memory: 2Gi
  volumes:
    - name: vpp-config
      configMap:
        name: vnf-vpp-cfg
    - name: agent-config
      configMap:
        name: vnf-agent-cfg
    - name: memif-sockets
      hostPath:
        path: /var/run/contiv
  nodeSelector:
    role: affinity

---
